**Make sure this file is saved to your local machine**

In [ ]:
import numpy as np
import pandas as pd
import requests
import csv
import sys
import os
import time

In [ ]:
!pip install --upgrade urllib3 requests
pip install comtradeapicall

Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (2.0.7)
Collecting urllib3
  Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.6/104.6 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2023.11.17)
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.7
    Uninstalling urllib3-2.0.7:
      Successfully uninstalled urllib3-2.0.7
Successfully installed urllib3-2.1.0

Requirement already satisfied: comtradeapicall in /Users/janezhang/opt/anaconda3/lib/python3.9/site-packages (1.2.1)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

#  Define Variables( Remember to create local directory before you start)

In [ ]:
reporter_code_list = pd.read_csv('Country_Code.csv', encoding='latin1')['Country Code']
year_list=np.array([2023]) #*Data Update
output_folder = r"...\Data"

'2019,2020,2021,2022,2023,'

In [ ]:
reporter_code_list

0        4
1      472
2        8
3       12
4       16
      ...
289    732
290      0
291    887
292    894
293    716
Name: Country Code, Length: 294, dtype: int64

# Define helper functions

In [ ]:
import comtradeapicall
def get_export(reporter_code,year):
    """https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv"""
    df = comtradeapicall.getFinalData("<COMTRADE_API_KEY>", typeCode='C', freqCode='A', clCode='HS', period=year,
                                             reporterCode=reporter_code, partner2Code = None, customsCode = None, motCode = None, cmdCode='ALL', flowCode='X', partnerCode = 0, maxRecords=50000)
    """
    download = s.get(CSV_URL, verify=False)
    decoded_content = download.content.decode('utf-8')
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
    df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]"""
    df = df[['cmdCode', 'fobvalue']]
    # only include six-digit commodity codes
    df=df[df["cmdCode"].apply(lambda x: len(str(x))==6)]
    if len(df)<20:
        raise ValueError
    df.to_csv(str(reporter_code)+".csv")
    return df

In [ ]:

def merge_all(year_list):
    #for year in year_list:
    year = 2023
    """sub_path=PATH
        # fetch all file pathes and reporter codes
        dir_series = pd.Series(os.listdir(sub_path))
        avail_reporter_code_list=dir_series.str.split(".",expand=True)[0]
"""
    # read in the first country
    first_ind = 2
    end_ind = 10
    try:

        print(str(reporter_code_list[0])+".csv")
        df=pd.read_csv(str(reporter_code_list[first_ind])+".csv")[["cmdCode","fobvalue"]]
        df.columns=["cmdCode",reporter_code_list.iloc[first_ind]]
        df = df.groupby('cmdCode').sum()
    except:
        print("nope")
    # append all other countries to df
    #len(reporter_code_list)
    for nxt in range(first_ind+1,len(reporter_code_list)):
        try:
            file_name = str(reporter_code_list[nxt])+".csv"
            print(file_name)
            nxt_df=pd.read_csv(file_name)[["cmdCode","fobvalue"]]
            nxt_df.columns=["cmdCode",reporter_code_list.iloc[nxt]]
            print(["cmdCode",reporter_code_list.iloc[nxt]])
            nxt_df = nxt_df.groupby('cmdCode').sum()
            df=df.merge(nxt_df,left_on='cmdCode', right_on='cmdCode',how='outer')

        except:
            print("No {}".format(reporter_code_list[nxt]))
            print(file_name)
    print(year)
    df.fillna(0,inplace=True)
    print(df.columns)
    df.to_csv(str(year)+"_mega.csv")
    return 200

In [ ]:
get_export(76,2022)

https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=76&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv
[['{ "statusCode": 401', ' "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API." }']]

IndexError: positional indexers are out-of-bounds

# **DATA RETRIEVAL**

In [ ]:

index=np.where(reporter_code_list==804)[0][0]
print(index)
print(reporter_code_list[index:])
for reporter_code in reporter_code_list:
#for reporter_code in reporter_code_list:
    for year in year_list:
        folder_path = "ECI Research"
        file_name = str(reporter_code)+".csv"
        file_path = os.path.join(folder_path, file_name)
        if os.path.exists(file_path)==False:
            time.sleep(10)
            try:
                get_export(reporter_code,year)
                print(".",end="")
            except KeyboardInterrupt:
                raise
            except:
                print("X",end="")
                print(reporter_code)
                pass
        else:
                print('exists')

273
273    804
274    784
275    826
276    834
277    581
278    858
279    849
280    850
281    842
282    841
283    860
284    548
285    862
286    704
287    876
288    879
289    732
290      0
291    887
292    894
293    716
Name: Country Code, dtype: int64
X4
X472
.X12
X16
..X660
X10
.X899
........X50
.X112
.X58
...X64
.X535
..X74
X80
X86
X92
...X837
.X108
.X471
.X120
.X129
..X148
....X162
X166
.X174
X178
X184
...X192
X531
..X200
X408
.....X588
X221
...X226
X232
...X697
X492
X234
X238
..X886
X278
X866
X720
X230
X280
X582
X590
X592
X868
X717
X736
X835
X810
X890
X836
X260
.X838
X254
.X583
.....X292
.X304
.X312
X316
.X324
X624
.X332
X334
X336
....X356
.X364
X368
........X296
..X473
.....X434
......X466
.X584
X474
..X175
.X496
.....X580
.X520
X524
X530
X532
.X536
X540
....X570
X574
X637
X290
.X527
.X577
.X568
.X585
.X598
.X459
..X612
.....X636
X638
.X643
X646
X647
X461
X652
X654
X659
X658
X662
X534
X666
..X674
.X457
...X891
.X694
X698
...X711
X90
X706
.X239
X728
.X839
..X729
....X760
.....X772
X776
...X795
X796
X798
.....X581
.X849
X850
.X841
.X548
X862
.X876
X879
X732
X0
X887
..

# **MERGING ALL COUNTRY DATA**

In [ ]:
merge_all(year_list)

4.csv
12.csv
No 12
12.csv
16.csv
No 16
16.csv
20.csv
['cmdCode', 20]
24.csv
['cmdCode', 24]
660.csv
No 660
660.csv
10.csv
No 10
10.csv
28.csv
['cmdCode', 28]
899.csv
No 899
899.csv
32.csv
['cmdCode', 32]
51.csv
['cmdCode', 51]
533.csv
['cmdCode', 533]
36.csv
['cmdCode', 36]
40.csv
['cmdCode', 40]
31.csv
['cmdCode', 31]
44.csv
['cmdCode', 44]
48.csv
['cmdCode', 48]
50.csv
No 50
50.csv
52.csv
['cmdCode', 52]
112.csv
No 112
112.csv
56.csv
['cmdCode', 56]
58.csv
No 58
58.csv
84.csv
['cmdCode', 84]
204.csv
['cmdCode', 204]
60.csv
['cmdCode', 60]
64.csv
No 64
64.csv
68.csv
['cmdCode', 68]
535.csv
No 535
535.csv
70.csv
['cmdCode', 70]
72.csv
['cmdCode', 72]
74.csv
No 74
74.csv
80.csv
No 80
80.csv
86.csv
No 86
86.csv
92.csv
No 92
92.csv
76.csv
['cmdCode', 76]
96.csv
['cmdCode', 96]
100.csv
['cmdCode', 100]
837.csv
No 837
837.csv
854.csv
['cmdCode', 854]
108.csv
No 108
108.csv
132.csv
['cmdCode', 132]
471.csv
No 471
471.csv
116.csv
['cmdCode', 116]
120.csv
No 120
120.csv
124.csv
['cmdCode', 124]
129.csv
No 129
129.csv
136.csv
['cmdCode', 136]
140.csv
['cmdCode', 140]
148.csv
No 148
148.csv
152.csv
['cmdCode', 152]
156.csv
['cmdCode', 156]
344.csv
['cmdCode', 344]
446.csv
['cmdCode', 446]
162.csv
No 162
162.csv
166.csv
No 166
166.csv
170.csv
['cmdCode', 170]
174.csv
No 174
174.csv
178.csv
No 178
178.csv
184.csv
No 184
184.csv
188.csv
['cmdCode', 188]
384.csv
['cmdCode', 384]
191.csv
['cmdCode', 191]
192.csv
No 192
192.csv
531.csv
No 531
531.csv
196.csv
['cmdCode', 196]
203.csv
['cmdCode', 203]
200.csv
No 200
200.csv
408.csv
No 408
408.csv
180.csv
['cmdCode', 180]
208.csv
['cmdCode', 208]
262.csv
['cmdCode', 262]
212.csv
['cmdCode', 212]
214.csv
['cmdCode', 214]
588.csv
No 588
588.csv
221.csv
No 221
221.csv
218.csv
['cmdCode', 218]
818.csv
['cmdCode', 818]
222.csv
['cmdCode', 222]
226.csv
No 226
226.csv
232.csv
No 232
232.csv
233.csv
['cmdCode', 233]
231.csv
['cmdCode', 231]
97.csv
['cmdCode', 97]
697.csv
No 697
697.csv
492.csv
No 492
492.csv
234.csv
No 234
234.csv
238.csv
No 238
238.csv
242.csv
['cmdCode', 242]
246.csv
['cmdCode', 246]
886.csv
No 886
886.csv
278.csv
No 278
278.csv
866.csv
No 866
866.csv
720.csv
No 720
720.csv
230.csv
No 230
230.csv
280.csv
No 280
280.csv
582.csv
No 582
582.csv
590.csv
No 590
590.csv
592.csv
No 592
592.csv
868.csv
No 868
868.csv
717.csv
No 717
717.csv
736.csv
No 736
736.csv
835.csv
No 835
835.csv
810.csv
No 810
810.csv
890.csv
No 890
890.csv
836.csv
No 836
836.csv
260.csv
No 260
260.csv
251.csv
['cmdCode', 251]
838.csv
No 838
838.csv
254.csv
No 254
254.csv
258.csv
['cmdCode', 258]
583.csv
No 583
583.csv
266.csv
['cmdCode', 266]
270.csv
['cmdCode', 270]
268.csv
['cmdCode', 268]
276.csv
['cmdCode', 276]
288.csv
['cmdCode', 288]
292.csv
No 292
292.csv
300.csv
['cmdCode', 300]
304.csv
No 304
304.csv
308.csv
['cmdCode', 308]
312.csv
No 312
312.csv
316.csv
No 316
316.csv
320.csv
['cmdCode', 320]
324.csv
No 324
324.csv
624.csv
No 624
624.csv
328.csv
['cmdCode', 328]
332.csv
No 332
332.csv
334.csv
No 334
334.csv
336.csv
No 336
336.csv
340.csv
['cmdCode', 340]
348.csv
['cmdCode', 348]
352.csv
['cmdCode', 352]
699.csv
['cmdCode', 699]
356.csv
No 356
356.csv
360.csv
['cmdCode', 360]
364.csv
No 364
364.csv
368.csv
No 368
368.csv
372.csv
['cmdCode', 372]
376.csv
['cmdCode', 376]
381.csv
['cmdCode', 381]
388.csv
['cmdCode', 388]
392.csv
['cmdCode', 392]
400.csv
['cmdCode', 400]
398.csv
['cmdCode', 398]
404.csv
['cmdCode', 404]
296.csv
No 296
296.csv
414.csv
['cmdCode', 414]
417.csv
['cmdCode', 417]
473.csv
No 473
473.csv
418.csv
['cmdCode', 418]
428.csv
['cmdCode', 428]
422.csv
['cmdCode', 422]
426.csv
['cmdCode', 426]
430.csv
['cmdCode', 430]
434.csv
No 434
434.csv
440.csv
['cmdCode', 440]
442.csv
['cmdCode', 442]
450.csv
['cmdCode', 450]
454.csv
['cmdCode', 454]
458.csv
['cmdCode', 458]
462.csv
['cmdCode', 462]
466.csv
No 466
466.csv
470.csv
['cmdCode', 470]
584.csv
No 584
584.csv
474.csv
No 474
474.csv
478.csv
['cmdCode', 478]
480.csv
['cmdCode', 480]
175.csv
No 175
175.csv
484.csv
['cmdCode', 484]
496.csv
No 496
496.csv
499.csv
['cmdCode', 499]
500.csv
['cmdCode', 500]
504.csv
['cmdCode', 504]
508.csv
['cmdCode', 508]
104.csv
['cmdCode', 104]
580.csv
No 580
580.csv
516.csv
['cmdCode', 516]
520.csv
No 520
520.csv
524.csv
No 524
524.csv
530.csv
No 530
530.csv
532.csv
No 532
532.csv
528.csv
['cmdCode', 528]
536.csv
No 536
536.csv
540.csv
No 540
540.csv
554.csv
['cmdCode', 554]
558.csv
['cmdCode', 558]
562.csv
['cmdCode', 562]
566.csv
['cmdCode', 566]
570.csv
No 570
570.csv
574.csv
No 574
574.csv
637.csv
No 637
637.csv
290.csv
No 290
290.csv
579.csv
['cmdCode', 579]
527.csv
No 527
527.csv
512.csv
['cmdCode', 512]
577.csv
No 577
577.csv
490.csv
['cmdCode', 490]
568.csv
No 568
568.csv
586.csv
['cmdCode', 586]
585.csv
No 585
585.csv
591.csv
['cmdCode', 591]
598.csv
No 598
598.csv
600.csv
['cmdCode', 600]
459.csv
No 459
459.csv
604.csv
['cmdCode', 604]
608.csv
['cmdCode', 608]
612.csv
No 612
612.csv
616.csv
['cmdCode', 616]
620.csv
['cmdCode', 620]
634.csv
['cmdCode', 634]
410.csv
['cmdCode', 410]
498.csv
['cmdCode', 498]
636.csv
No 636
636.csv
638.csv
No 638
638.csv
642.csv
['cmdCode', 642]
643.csv
No 643
643.csv
646.csv
No 646
646.csv
647.csv
No 647
647.csv
461.csv
No 461
461.csv
652.csv
No 652
652.csv
654.csv
No 654
654.csv
659.csv
No 659
659.csv
658.csv
No 658
658.csv
662.csv
No 662
662.csv
534.csv
No 534
534.csv
666.csv
No 666
666.csv
670.csv
['cmdCode', 670]
882.csv
['cmdCode', 882]
674.csv
No 674
674.csv
678.csv
['cmdCode', 678]
457.csv
No 457
457.csv
682.csv
['cmdCode', 682]
686.csv
['cmdCode', 686]
688.csv
['cmdCode', 688]
891.csv
No 891
891.csv
690.csv
['cmdCode', 690]
694.csv
No 694
694.csv
698.csv
No 698
698.csv
702.csv
['cmdCode', 702]
703.csv
['cmdCode', 703]
705.csv
['cmdCode', 705]
711.csv
No 711
711.csv
90.csv
No 90
90.csv
706.csv
No 706
706.csv
710.csv
['cmdCode', 710]
239.csv
No 239
239.csv
728.csv
No 728
728.csv
724.csv
['cmdCode', 724]
839.csv
No 839
839.csv
144.csv
['cmdCode', 144]
275.csv
['cmdCode', 275]
729.csv
No 729
729.csv
740.csv
['cmdCode', 740]
748.csv
['cmdCode', 748]
752.csv
['cmdCode', 752]
757.csv
['cmdCode', 757]
760.csv
No 760
760.csv
762.csv
['cmdCode', 762]
807.csv
['cmdCode', 807]
764.csv
['cmdCode', 764]
626.csv
['cmdCode', 626]
768.csv
['cmdCode', 768]
772.csv
No 772
772.csv
776.csv
No 776
776.csv
780.csv
['cmdCode', 780]
788.csv
['cmdCode', 788]
792.csv
['cmdCode', 792]
795.csv
No 795
795.csv
796.csv
No 796
796.csv
798.csv
No 798
798.csv
800.csv
['cmdCode', 800]
804.csv
['cmdCode', 804]
784.csv
['cmdCode', 784]
826.csv
['cmdCode', 826]
834.csv
['cmdCode', 834]
581.csv
No 581
581.csv
858.csv
['cmdCode', 858]
849.csv
No 849
849.csv
850.csv
No 850
850.csv
842.csv
['cmdCode', 842]
841.csv
No 841
841.csv
860.csv
['cmdCode', 860]
548.csv
No 548
548.csv
862.csv
No 862
862.csv
704.csv
['cmdCode', 704]
876.csv
No 876
876.csv
879.csv
No 879
879.csv
732.csv
No 732
732.csv
0.csv
No 0
0.csv
887.csv
No 887
887.csv
894.csv
['cmdCode', 894]
716.csv
['cmdCode', 716]
2023
Index([  8,  20,  24,  28,  32,  51, 533,  36,  40,  31,
       ...
       804, 784, 826, 834, 858, 842, 860, 704, 894, 716],
      dtype='object', length=155)

200

In [ ]:
mydf.columns

Index(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'period',
       'reporterCode', 'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc',
       'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code',
       'partner2ISO', 'partner2Desc', 'classificationCode',
       'classificationSearchCode', 'isOriginalClassification', 'cmdCode',
       'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc',
       'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty',
       'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty',
       'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt',
       'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue',
       'legacyEstimationFlag', 'isReported', 'isAggregate'],
      dtype='object')

In [ ]:
df= mydf
df = df.iloc[1:,[20,29]]
df
#df[df["cmdCode"].apply(lambda x: len(str(x))==6)]['cmdCode']

      cmdCode  qtyUnitCode
1          01           -1
2          09           -1
3          48           -1
4          73           -1
5          79           -1
...       ...          ...
26235  293920            8
26236  731816            8
26237    0209            8
26238  020910            8
26239  300650            8

[26239 rows x 2 columns]

In [ ]:
"""import requests

url_list = [
    'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=4&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv',
    'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=472&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv',
    # ... (other URLs)
]

for url in url_list:
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for bad responses (4xx or 5xx)

        # Now you can work with the content of the response, for example:
        content = response.text
        # Do something with the content, e.g., save it to a file or process it further


        print(f"Successfully opened URL: {url}")

    except requests.exceptions.RequestException as e:
        print(f"Failed to open URL: {url}\nError: {e}")"""

Successfully opened URL: https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=4&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv
Successfully opened URL: https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=472&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv

In [ ]:
year=2022
reporter_code=152
CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'
#Commented out getting list from requests and added a direct import for the csv - Jane

with requests.Session() as s:
  download = s.get(CSV_URL)
  decoded_content = download.content.decode('utf-8')
  cr = csv.reader(decoded_content.splitlines(), delimiter=',')
  my_list = list(cr)
  print(my_list)
df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
df.columns=["commodity_code","dollar_value"]
      # only include six-digit commodity codes
df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
if len(df)<20:
  raise ValueError
df.to_csv(PATH+"/"+"test"+"/"+str(reporter_code)+".csv")
#changed path to fix error & created test folder for test files for each country - Navia

[['Classification', 'Year', 'Period', 'Period Desc.', 'Aggregate Level', 'Is Leaf Code', 'Trade Flow Code', 'Trade Flow', 'Reporter Code', 'Reporter', 'Reporter ISO', 'Partner Code', 'Partner', 'Partner ISO', '2nd Partner Code', '2nd Partner', '2nd Partner ISO', 'Customs Proc. Code', 'Customs', 'Mode of Transport Code', 'Mode of Transport', 'Commodity Code', 'Commodity', 'Qty Unit Code', 'Qty Unit', 'Qty', 'Alt Qty Unit Code', 'Alt Qty Unit', 'Alt Qty', 'Netweight (kg)', 'Gross weight (kg)', 'Trade Value (US$)', 'CIF Trade Value (US$)', 'FOB Trade Value (US$)', 'Flag'], ['H6', '2022', '2022', '2022', '2', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '01', 'Animals; live', '1', 'No Quantity', '0', '', '', '', '', '', '27293605', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0101', 'Horses, asses, mules and hinnies; live', '1', 'No Quantity', '0', '', '', '', '', '', '7895204', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010121', 'Horses; live, pure-bred breeding animals', '5', 'Number of items', '10', '', '', '', '1036', '', '70778', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010129', 'Horses; live, other than pure-bred breeding animals', '5', 'Number of items', '89', '', '', '', '177269', '', '7812937', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010190', 'Mules and hinnies; live', '1', 'No Quantity', '0', '', '', '', '', '', '11488', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0102', 'Bovine animals; live', '5', 'Number of items', '15812', '', '', '', '4370129', '', '14924424', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010221', 'Cattle; live, pure-bred breeding animals', '5', 'Number of items', '11964', '', '', '', '3128106', '', '11229668', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010229', 'Cattle; live, other than pure-bred breeding animals', '5', 'Number of items', '3848', '', '', '', '1242022', '', '3694756', '', '', '4'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0104', 'Sheep and goats; live', '5', 'Number of items', '29', '', '', '', '13359', '', '43500', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010410', 'Sheep; live', '5', 'Number of items', '29', '', '', '', '13359', '', '43500', '', '', '4'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0105', 'Poultry; live, fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls', '1', 'No Quantity', '0', '', '', '', '14', '', '927', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010511', 'Poultry; live, fowls of the species Gallus domesticus, weighing not more than 185g', '1', 'No Quantity', '0', '', '', '', '14', '', '927', '', '', '4'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0106', 'Animals; live, n.e.c. in chapter 01', '5', 'Number of items', '29204', '', '', '', '', '', '4429548', '', '', '2'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010613', 'Mammals; live, camels and other camelids (Camelidae)', '5', 'Number of items', '14868', '', '', '', '', '', '3399916', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010619', 'Mammals; live, other than primates, whales, dolphins, porpoises (mammals of the order Cetacea); manatees, dugongs (mammals of the order Sirenia); seals, sea lions, walruses (mammals of the suborder Pinnipedia), camels, other camelids, rabbits and hares', '5', 'Number of items', '2', '', '', '', '0', '', '100', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010641', 'Insects; live, bees', '5', 'Number of items', '13198', '', '', '', '37963', '', '424001', '', '', '4'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '010690', 'Animals; live, n.e.c. in chapter 01, other than mammals, reptiles, birds and insects', '1', 'No Quantity', '0', '', '', '', '13943', '', '605531', '', '', '4'], ['H6', '2022', '2022', '2022', '2', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '02', 'Meat and edible meat offal', '1', 'No Quantity', '0', '', '', '', '0', '', '1522673516', '', '', '4'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0201', 'Meat of bovine animals; fresh or chilled', '8', 'Weight in kilograms', '243015', '', '', '', '243015', '', '5794477', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020120', 'Meat; of bovine animals, cuts with bone in (excluding carcasses and half-carcasses), fresh or chilled', '8', 'Weight in kilograms', '18188', '', '', '', '18188', '', '570843', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020130', 'Meat; of bovine animals, boneless cuts, fresh or chilled', '8', 'Weight in kilograms', '224826', '', '', '', '224826', '', '5223634', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0202', 'Meat of bovine animals; frozen', '8', 'Weight in kilograms', '24039616', '', '', '', '24039616', '', '123021056', '', '', '6'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020220', 'Meat; of bovine animals, cuts with bone in (excluding carcasses and half-carcasses), frozen', '8', 'Weight in kilograms', '18589683', '', '', '', '18589683', '', '89285180', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020230', 'Meat; of bovine animals, boneless cuts, frozen', '8', 'Weight in kilograms', '5449932', '', '', '', '5449932', '', '33735875', '', '', '6'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0203', 'Meat of swine; fresh, chilled or frozen', '8', 'Weight in kilograms', '176895950', '', '', '', '176895950', '', '516520860', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020322', 'Meat; of swine, hams, shoulders and cuts thereof, with bone in, frozen', '8', 'Weight in kilograms', '34989154', '', '', '', '34989154', '', '70617550', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020329', 'Meat; of swine, n.e.c. in item no. 0203.2, frozen', '8', 'Weight in kilograms', '141906796', '', '', '', '141906796', '', '445903310', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0204', 'Meat of sheep or goats; fresh, chilled or frozen', '8', 'Weight in kilograms', '5716718', '', '', '', '5716718', '', '42858840', '', '', '6'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020422', 'Meat; of sheep (including lamb), cuts with bone in (excluding carcasses and half-carcasses), fresh or chilled', '8', 'Weight in kilograms', '51887', '', '', '', '51887', '', '663751', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020423', 'Meat; of sheep (including lamb), boneless cuts, fresh or chilled', '8', 'Weight in kilograms', '25834', '', '', '', '25834', '', '348294', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020430', 'Meat; of sheep, lamb carcasses and half-carcasses, frozen', '8', 'Weight in kilograms', '1322384', '', '', '', '1322384', '', '9325534', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020442', 'Meat; of sheep (including lamb), cuts with bone in (excluding carcasses and half-carcasses), frozen', '8', 'Weight in kilograms', '3793936', '', '', '', '3793936', '', '27068067', '', '', '6'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020443', 'Meat; of sheep (including lamb), boneless cuts, frozen', '8', 'Weight in kilograms', '522675', '', '', '', '522675', '', '5453191', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0206', 'Edible offal of bovine animals, swine, sheep, goats, horses, asses, mules or hinnies; fresh, chilled or frozen', '8', 'Weight in kilograms', '58962992', '', '', '', '58962992', '', '98286495', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020610', 'Offal, edible; of bovine animals, fresh or chilled', '8', 'Weight in kilograms', '253', '', '', '', '253', '', '6781', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020621', 'Offal, edible; of bovine animals, tongues, frozen', '8', 'Weight in kilograms', '333581', '', '', '', '333581', '', '3688760', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020622', 'Offal, edible; of bovine animals, livers, frozen', '8', 'Weight in kilograms', '349', '', '', '', '349', '', '869', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020629', 'Offal, edible; of bovine animals, (other than tongues and livers), frozen', '8', 'Weight in kilograms', '766539', '', '', '', '766539', '', '2893677', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020630', 'Offal, edible; of swine, fresh or chilled', '8', 'Weight in kilograms', '10260', '', '', '', '10260', '', '11697', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020641', 'Offal, edible; of swine, livers, frozen', '8', 'Weight in kilograms', '4000675', '', '', '', '4000675', '', '2556844', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020649', 'Offal, edible; of swine, (other than livers), frozen', '8', 'Weight in kilograms', '53801854', '', '', '', '53801854', '', '88923786', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020680', 'Offal, edible; of sheep, goats, horses, asses, mules or hinnies, fresh or chilled', '8', 'Weight in kilograms', '1080', '', '', '', '1080', '', '2146', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020690', 'Offal, edible; of sheep, goats, horses, asses, mules or hinnies, frozen', '8', 'Weight in kilograms', '48398', '', '', '', '48398', '', '201931', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0207', 'Meat and edible offal of poultry; of the poultry of heading no. 0105, (i.e. fowls of the species Gallus domesticus), fresh, chilled or frozen', '8', 'Weight in kilograms', '171890060', '', '', '', '171890060', '', '700236174', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020712', 'Meat and edible offal; of fowls of the species Gallus domesticus, not cut in pieces, frozen', '8', 'Weight in kilograms', '635608', '', '', '', '635608', '', '800609', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020714', 'Meat and edible offal; of fowls of the species Gallus domesticus, cuts and offal, frozen', '8', 'Weight in kilograms', '143034628', '', '', '', '143034628', '', '525298297', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020725', 'Meat and edible offal; of turkeys, not cut in pieces, frozen', '8', 'Weight in kilograms', '80533', '', '', '', '80533', '', '342670', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020726', 'Meat and edible offal; of turkeys, cuts and offal, fresh or chilled', '8', 'Weight in kilograms', '24000', '', '', '', '24000', '', '26397', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020727', 'Meat and edible offal; of turkeys, cuts and offal, frozen', '8', 'Weight in kilograms', '28115290', '', '', '', '28115290', '', '173768200', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0208', 'Meat and edible meat offal, n.e.c. in chapter 2; fresh, chilled or frozen', '8', 'Weight in kilograms', '20721', '', '', '', '20721', '', '178864', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020810', 'Meat and edible meat offal; of rabbits or hares, fresh, chilled or frozen', '8', 'Weight in kilograms', '20721', '', '', '', '20721', '', '178864', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0209', 'Pig fat, free of lean meat, and poultry fat, not rendered or otherwise extracted, fresh, chilled, frozen, salted, in brine, dried or smoked', '1', 'No Quantity', '0', '', '', '', '0', '', '35348295', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '020910', 'Fat; pig fat, free of lean meat, not rendered or otherwise extracted, fresh, chilled, frozen, salted, in brine, dried or smoked', '8', 'Weight in kilograms', '30595090', '', '', '', '30595090', '', '35347115', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0210', 'Meat and edible meat offal; salted, in brine, dried or smoked; edible flours and meals of meat or meat offal', '8', 'Weight in kilograms', '20200', '', '', '', '20200', '', '428450', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '021020', 'Meat; salted, in brine, dried or smoked, of bovine animals', '8', 'Weight in kilograms', '19900', '', '', '', '19900', '', '419600', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '021099', 'Meat and edible meat offal; salted, in brine, dried or smoked, and edible flours and meals of meat or meat offal, other than of primates, whales, dolphins, porpoises, manatees, dugongs, seals, sea lions, walruses, reptiles (including snakes and turtles)', '8', 'Weight in kilograms', '300', '', '', '', '300', '', '8850', '', '', '0'], ['H6', '2022', '2022', '2022', '2', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '03', 'Fish and crustaceans, molluscs and other aquatic invertebrates', '1', 'No Quantity', '0', '', '', '', '0', '', '7471315121', '', '', '4'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0301', 'Fish; live', '8', 'Weight in kilograms', '28087', '', '', '', '28087', '', '110570', '', '', '6'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '030193', 'Fish; live, carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.)', '8', 'Weight in kilograms', '28080', '', '', '', '28080', '', '82547', '', '', '6'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '030199', 'Fish; live, n.e.c. in heading 0301', '8', 'Weight in kilograms', '7', '', '', '', '7', '', '28022', '', '', '0'], ['H6', '2022', '2022', '2022', '4', '0', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '0302', 'Fish; fresh or chilled, excluding fish fillets and other fish meat of heading 0304', '8', 'Weight in kilograms', '131669661', '', '', '', '131669661', '', '1056863644', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '030211', 'Fish; fresh or chilled, trout (Salmo trutta, Oncorhynchus mykiss, Oncorhynchus clarki, Oncorhynchus aguabonita, Oncorhynchus gilae, Oncorhynchus apache and Oncorhynchus chrysogaster), excluding fillets, fish meat of 0304, and edible fish offal of 0302.9', '8', 'Weight in kilograms', '242395', '', '', '', '242395', '', '1961972', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '030213', 'Fish; fresh or chilled, Pacific salmon (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou, Oncorhynchus rhodurus), not fillets, meat of 0304, and edible fish offal of 0302.9', '8', 'Weight in kilograms', '2051884', '', '', '', '2051884', '', '14028712', '', '', '0'], ['H6', '2022', '2022', '2022', '6', '1', '2', 'Export', '152', 'Chile', 'CHL', '0', 'World', 'WLD', '', '', '', '', '', '', '', '030214', 'Fish; fresh or chilled, Atlantic salmon (Salmo salar) and Danube salmon (Hucho hucho), excluding fillets, fish meat of 0304, and edible fish offal of subheadings 0302.91 to 0302.99', '8', 'Weight in kilograms', '125865368', '', '', '', '125865368', '', '102564

OSError: Cannot save file into a non-existent directory: 'drive/My Drive/ECI Research/5. Datasets/2022 Fall - Data/test'

In [ ]:
#test create helper func
year=2022
reporter_code=152
CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'
#Commented out getting list from requests and added a direct import for the csv - Jane

with requests.Session() as s:
  download = s.get(CSV_URL)
  decoded_content = download.content.decode('utf-8')
  cr = csv.reader(decoded_content.splitlines(), delimiter=',')
  my_list = list(cr)
  print(my_list)
my_list = pd.read_csv(PATH + "comtrade2021.csv")
df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
df.columns=["commodity_code","dollar_value"]
      # only include six-digit commodity codes
df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
if len(df)<20:
  raise ValueError
df.to_csv(PATH+"/"+"test"+"/"+str(reporter_code)+".csv")
#changed path to fix error & created test folder for test files for each country - Navia

def get_export(reporter_code,year):
    CSV_URL = 'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps='+str(year)+'&r='+str(reporter_code)+'&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'

    with requests.Session() as s:
        download = s.get(CSV_URL, verify=False)
        decoded_content = download.content.decode('utf-8')
        cr = csv.reader(decoded_content.splitlines(), delimiter=',')
        my_list = list(cr)
        df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
        df.columns=["commodity_code","dollar_value"]
        # only include six-digit commodity codes
        df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
        if len(df)<20:
            raise ValueError
        df.to_csv(PATH+"/"+str(reporter_code)+".csv")
    return df

SSLError: ignored

In [ ]:
CSV_URL

'https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=2022&r=152&p=0&rg=2&cc=ALL&uitoken=<COMTRADE_UITOKEN>&fmt=csv'

In [ ]:
# Function to read in all csvs from local, merge into a mega csv, and save to local.

def merge_all(year_list):
    #for year in year_list:
    year = 2024
    """sub_path=PATH
        # fetch all file pathes and reporter codes
        dir_series = pd.Series(os.listdir(sub_path))
        avail_reporter_code_list=dir_series.str.split(".",expand=True)[0]
"""
    # read in the first country
    first_ind = 2
    try:

        print(str(reporter_code_list[0])+"_"+str(year)+".csv")
        df=pd.read_csv(str(reporter_code_list[first_ind])+"_"+str(year)+".csv")[["commodity_code","dollar_value"]]
        df.columns=["commodity_code",reporter_code_list.iloc[first_ind]]
    except:
        print("nope")
    # append all other countries to df
    for nxt in range(first_ind+1,len(reporter_code_list)):
        try:
            file_name = str(reporter_code_list[nxt])+"_"+str(year)+".csv"
            print(file_name)
            nxt_df=pd.read_csv(file_name)[["commodity_code","dollar_value"]]
            nxt_df.columns=["commodity_code",reporter_code_list.iloc[nxt]]
            print(["commodity_code",reporter_code_list.iloc[nxt]])
            df=df.merge(nxt_df,left_on='commodity_code', right_on='commodity_code',how='outer')

        except:
            print("No {}".format(reporter_code_list[nxt]))
            print(file_name)
    print(year)
    df.fillna(0,inplace=True)
    print(df.columns)
    df.to_csv(str(year)+"_mega.csv")
    return 200

In [ ]:
merge_all(year_list)

4_2022.csv
12_2022.csv
No 12
12_2022.csv
16_2022.csv
No 16
16_2022.csv
20_2022.csv
['commodity_code', 20]
24_2022.csv
['commodity_code', 24]
660_2022.csv
No 660
660_2022.csv
10_2022.csv
No 10
10_2022.csv
28_2022.csv
['commodity_code', 28]
899_2022.csv
No 899
899_2022.csv
32_2022.csv
['commodity_code', 32]
51_2022.csv
['commodity_code', 51]
533_2022.csv
['commodity_code', 533]
36_2022.csv
['commodity_code', 36]
40_2022.csv
['commodity_code', 40]
31_2022.csv
['commodity_code', 31]
44_2022.csv
['commodity_code', 44]
48_2022.csv
['commodity_code', 48]
50_2022.csv
No 50
50_2022.csv
52_2022.csv
['commodity_code', 52]
112_2022.csv
No 112
112_2022.csv
56_2022.csv
['commodity_code', 56]
58_2022.csv
No 58
58_2022.csv
84_2022.csv
['commodity_code', 84]
204_2022.csv
['commodity_code', 204]
60_2022.csv
['commodity_code', 60]
64_2022.csv
No 64
64_2022.csv
68_2022.csv
['commodity_code', 68]
535_2022.csv
No 535
535_2022.csv
70_2022.csv
['commodity_code', 70]
72_2022.csv
['commodity_code', 72]
74_2022.csv
No 74
74_2022.csv
80_2022.csv
No 80
80_2022.csv
86_2022.csv
No 86
86_2022.csv
92_2022.csv
No 92
92_2022.csv
76_2022.csv
['commodity_code', 76]
96_2022.csv
['commodity_code', 96]
100_2022.csv
['commodity_code', 100]
837_2022.csv
No 837
837_2022.csv
854_2022.csv
['commodity_code', 854]
108_2022.csv
['commodity_code', 108]
132_2022.csv
['commodity_code', 132]
471_2022.csv
No 471
471_2022.csv
116_2022.csv
No 116
116_2022.csv
120_2022.csv
No 120
120_2022.csv
124_2022.csv
['commodity_code', 124]
129_2022.csv
No 129
129_2022.csv
136_2022.csv
No 136
136_2022.csv
140_2022.csv
['commodity_code', 140]
148_2022.csv
No 148
148_2022.csv
152_2022.csv
['commodity_code', 152]
156_2022.csv
['commodity_code', 156]
344_2022.csv
['commodity_code', 344]
446_2022.csv
['commodity_code', 446]
162_2022.csv
No 162
162_2022.csv
166_2022.csv
No 166
166_2022.csv
170_2022.csv
['commodity_code', 170]
174_2022.csv
No 174
174_2022.csv
178_2022.csv
No 178
178_2022.csv
184_2022.csv
No 184
184_2022.csv
188_2022.csv
['commodity_code', 188]
384_2022.csv
['commodity_code', 384]
191_2022.csv
['commodity_code', 191]
192_2022.csv
No 192
192_2022.csv
531_2022.csv
No 531
531_2022.csv
196_2022.csv
['commodity_code', 196]
203_2022.csv
['commodity_code', 203]
200_2022.csv
No 200
200_2022.csv
408_2022.csv
No 408
408_2022.csv
180_2022.csv
['commodity_code', 180]
208_2022.csv
['commodity_code', 208]
262_2022.csv
No 262
262_2022.csv
212_2022.csv
No 212
212_2022.csv
214_2022.csv
['commodity_code', 214]
588_2022.csv
No 588
588_2022.csv
221_2022.csv
No 221
221_2022.csv
218_2022.csv
['commodity_code', 218]
818_2022.csv
['commodity_code', 818]
222_2022.csv
['commodity_code', 222]
226_2022.csv
No 226
226_2022.csv
232_2022.csv
No 232
232_2022.csv
233_2022.csv
['commodity_code', 233]
231_2022.csv
['commodity_code', 231]
97_2022.csv
['commodity_code', 97]
697_2022.csv
No 697
697_2022.csv
492_2022.csv
No 492
492_2022.csv
234_2022.csv
No 234
234_2022.csv
238_2022.csv
No 238
238_2022.csv
242_2022.csv
['commodity_code', 242]
246_2022.csv
['commodity_code', 246]
886_2022.csv
No 886
886_2022.csv
278_2022.csv
No 278
278_2022.csv
866_2022.csv
No 866
866_2022.csv
720_2022.csv
No 720
720_2022.csv
230_2022.csv
No 230
230_2022.csv
280_2022.csv
No 280
280_2022.csv
582_2022.csv
No 582
582_2022.csv
590_2022.csv
No 590
590_2022.csv
592_2022.csv
No 592
592_2022.csv
868_2022.csv
No 868
868_2022.csv
717_2022.csv
No 717
717_2022.csv
736_2022.csv
No 736
736_2022.csv
835_2022.csv
No 835
835_2022.csv
810_2022.csv
No 810
810_2022.csv
890_2022.csv
No 890
890_2022.csv
836_2022.csv
No 836
836_2022.csv
260_2022.csv
No 260
260_2022.csv
251_2022.csv
['commodity_code', 251]
838_2022.csv
No 838
838_2022.csv
254_2022.csv
No 254
254_2022.csv
258_2022.csv
['commodity_code', 258]
583_2022.csv
No 583
583_2022.csv
266_2022.csv
No 266
266_2022.csv
270_2022.csv
No 270
270_2022.csv
268_2022.csv
['commodity_code', 268]
276_2022.csv
['commodity_code', 276]
288_2022.csv
No 288
288_2022.csv
292_2022.csv
No 292
292_2022.csv
300_2022.csv
['commodity_code', 300]
304_2022.csv
No 304
304_2022.csv
308_2022.csv
['commodity_code', 308]
312_2022.csv
No 312
312_2022.csv
316_2022.csv
No 316
316_2022.csv
320_2022.csv
['commodity_code', 320]
324_2022.csv
No 324
324_2022.csv
624_2022.csv
No 624
624_2022.csv
328_2022.csv
['commodity_code', 328]
332_2022.csv
No 332
332_2022.csv
334_2022.csv
No 334
334_2022.csv
336_2022.csv
No 336
336_2022.csv
340_2022.csv
No 340
340_2022.csv
348_2022.csv
['commodity_code', 348]
352_2022.csv
['commodity_code', 352]
699_2022.csv
['commodity_code', 699]
356_2022.csv
No 356
356_2022.csv
360_2022.csv
['commodity_code', 360]
364_2022.csv
No 364
364_2022.csv
368_2022.csv
No 368
368_2022.csv
372_2022.csv
['commodity_code', 372]
376_2022.csv
['commodity_code', 376]
381_2022.csv
['commodity_code', 381]
388_2022.csv
['commodity_code', 388]
392_2022.csv
['commodity_code', 392]
400_2022.csv
['commodity_code', 400]
398_2022.csv
['commodity_code', 398]
404_2022.csv
['commodity_code', 404]
296_2022.csv
No 296
296_2022.csv
414_2022.csv
['commodity_code', 414]
417_2022.csv
['commodity_code', 417]
473_2022.csv
No 473
473_2022.csv
418_2022.csv
No 418
418_2022.csv
428_2022.csv
['commodity_code', 428]
422_2022.csv
['commodity_code', 422]
426_2022.csv
['commodity_code', 426]
430_2022.csv
No 430
430_2022.csv
434_2022.csv
No 434
434_2022.csv
440_2022.csv
['commodity_code', 440]
442_2022.csv
['commodity_code', 442]
450_2022.csv
['commodity_code', 450]
454_2022.csv
['commodity_code', 454]
458_2022.csv
['commodity_code', 458]
462_2022.csv
['commodity_code', 462]
466_2022.csv
No 466
466_2022.csv
470_2022.csv
['commodity_code', 470]
584_2022.csv
No 584
584_2022.csv
474_2022.csv
No 474
474_2022.csv
478_2022.csv
['commodity_code', 478]
480_2022.csv
['commodity_code', 480]
175_2022.csv
No 175
175_2022.csv
484_2022.csv
['commodity_code', 484]
496_2022.csv
['commodity_code', 496]
499_2022.csv
['commodity_code', 499]
500_2022.csv
['commodity_code', 500]
504_2022.csv
['commodity_code', 504]
508_2022.csv
['commodity_code', 508]
104_2022.csv
['commodity_code', 104]
580_2022.csv
No 580
580_2022.csv
516_2022.csv
['commodity_code', 516]
520_2022.csv
No 520
520_2022.csv
524_2022.csv
['commodity_code', 524]
530_2022.csv
No 530
530_2022.csv
532_2022.csv
No 532
532_2022.csv
528_2022.csv
['commodity_code', 528]
536_2022.csv
No 536
536_2022.csv
540_2022.csv
No 540
540_2022.csv
554_2022.csv
['commodity_code', 554]
558_2022.csv
['commodity_code', 558]
562_2022.csv
['commodity_code', 562]
566_2022.csv
['commodity_code', 566]
570_2022.csv
No 570
570_2022.csv
574_2022.csv
No 574
574_2022.csv
637_2022.csv
No 637
637_2022.csv
290_2022.csv
No 290
290_2022.csv
579_2022.csv
['commodity_code', 579]
527_2022.csv
No 527
527_2022.csv
512_2022.csv
['commodity_code', 512]
577_2022.csv
No 577
577_2022.csv
490_2022.csv
['commodity_code', 490]
568_2022.csv
No 568
568_2022.csv
586_2022.csv
['commodity_code', 586]
585_2022.csv
No 585
585_2022.csv
591_2022.csv
['commodity_code', 591]
598_2022.csv
No 598
598_2022.csv
600_2022.csv
['commodity_code', 600]
459_2022.csv
No 459
459_2022.csv
604_2022.csv
['commodity_code', 604]
608_2022.csv
['commodity_code', 608]
612_2022.csv
No 612
612_2022.csv
616_2022.csv
['commodity_code', 616]
620_2022.csv
['commodity_code', 620]
634_2022.csv
['commodity_code', 634]
410_2022.csv
['commodity_code', 410]
498_2022.csv
['commodity_code', 498]
636_2022.csv
No 636
636_2022.csv
638_2022.csv
No 638
638_2022.csv
642_2022.csv
['commodity_code', 642]
643_2022.csv
No 643
643_2022.csv
646_2022.csv
['commodity_code', 646]
647_2022.csv
No 647
647_2022.csv
461_2022.csv
No 461
461_2022.csv
652_2022.csv
No 652
652_2022.csv
654_2022.csv
No 654
654_2022.csv
659_2022.csv
No 659
659_2022.csv
658_2022.csv
No 658
658_2022.csv
662_2022.csv
No 662
662_2022.csv
534_2022.csv
No 534
534_2022.csv
666_2022.csv
No 666
666_2022.csv
670_2022.csv
No 670
670_2022.csv
882_2022.csv
No 882
882_2022.csv
674_2022.csv
No 674
674_2022.csv
678_2022.csv
['commodity_code', 678]
457_2022.csv
No 457
457_2022.csv
682_2022.csv
No 682
682_2022.csv
686_2022.csv
['commodity_code', 686]
688_2022.csv
['commodity_code', 688]
891_2022.csv
No 891
891_2022.csv
690_2022.csv
No 690
690_2022.csv
694_2022.csv
No 694
694_2022.csv
698_2022.csv
No 698
698_2022.csv
702_2022.csv
['commodity_code', 702]
703_2022.csv

['commodity_code', 703]
705_2022.csv
['commodity_code', 705]
711_2022.csv
No 711
711_2022.csv
90_2022.csv
No 90
90_2022.csv
706_2022.csv
No 706
706_2022.csv
710_2022.csv
['commodity_code', 710]
239_2022.csv
No 239
239_2022.csv
728_2022.csv
No 728
728_2022.csv
724_2022.csv
['commodity_code', 724]
839_2022.csv
No 839
839_2022.csv
144_2022.csv
['commodity_code', 144]
275_2022.csv
No 275
275_2022.csv
729_2022.csv
No 729
729_2022.csv
740_2022.csv
['commodity_code', 740]
748_2022.csv
No 748
748_2022.csv
752_2022.csv
['commodity_code', 752]
757_2022.csv
['commodity_code', 757]
760_2022.csv
No 760
760_2022.csv
762_2022.csv
['commodity_code', 762]
807_2022.csv
['commodity_code', 807]
764_2022.csv
['commodity_code', 764]
626_2022.csv
['commodity_code', 626]
768_2022.csv
['commodity_code', 768]
772_2022.csv
No 772
772_2022.csv
776_2022.csv
No 776
776_2022.csv
780_2022.csv
['commodity_code', 780]
788_2022.csv
['commodity_code', 788]
792_2022.csv
['commodity_code', 792]
795_2022.csv
No 795
795_2022.csv
796_2022.csv
No 796
796_2022.csv
798_2022.csv
No 798
798_2022.csv
800_2022.csv
No 800
800_2022.csv
804_2022.csv
['commodity_code', 804]
784_2022.csv
['commodity_code', 784]
826_2022.csv
['commodity_code', 826]
834_2022.csv
['commodity_code', 834]
581_2022.csv
No 581
581_2022.csv
858_2022.csv
['commodity_code', 858]
849_2022.csv
No 849
849_2022.csv
850_2022.csv
No 850
850_2022.csv
842_2022.csv
['commodity_code', 842]
841_2022.csv
No 841
841_2022.csv
860_2022.csv
['commodity_code', 860]
548_2022.csv
No 548
548_2022.csv
862_2022.csv
No 862
862_2022.csv
704_2022.csv
['commodity_code', 704]
876_2022.csv
No 876
876_2022.csv
879_2022.csv
No 879
879_2022.csv
732_2022.csv
No 732
732_2022.csv
0_2022.csv
No 0
0_2022.csv
887_2022.csv
No 887
887_2022.csv
894_2022.csv
['commodity_code', 894]
716_2022.csv
['commodity_code', 716]
2022
Index(['commodity_code',                8,               20,               24,
                     28,               32,               51,              533,
                     36,               40,
       ...
                    804,              784,              826,              834,
                    858,              842,              860,              704,
                    894,              716],
      dtype='object', length=143)

200

In [ ]:
    SERVICE_URL="https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps="+str(year)+"&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>"
SERVICE_URL

'https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps=2020&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>'

In [ ]:
# Function to add a service column to the mega csv and save to local
def get_service(year=2023):
    SERVICE_URL="https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps="+str(year)+"&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>"
    #with requests.Session() as s:
        #download = s.get(SERVICE_URL)
        #decoded_content = download.content.decode('utf-8')
        #cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
    df=pd.DataFrame(np.array(my_list))
    df=df.iloc[1:,[1,8,20]]
    df.columns=["year","reporter_code","dollar_value"]
    return df

In [ ]:
get_service(year=2022)

IndexError: positional indexers are out-of-bounds

In [ ]:
#Navia re-coded version

def get_service(year=2021):
    #SERVICE_URL="https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps="+str(year)+"&r=all&p=0&rg=2&cc=200&uitoken=<COMTRADE_UITOKEN>"
    df = comtradeapicall.getFinalData("<COMTRADE_API_KEY>", typeCode='S', freqCode='A', clCode='EB02', period=year,
                                             reporterCode='ALL', partner2Code = None, customsCode = None, motCode = None, cmdCode='ALL', flowCode='X', partnerCode = 0, maxRecords=50000)

    #with requests.Session() as s:
        #download = s.get(CSV_URL)
        #decoded_content = download.content.decode('utf-8')
        #cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = pd.read_csv("comtrade2021.csv")
    df=pd.DataFrame(np.array(my_list)).iloc[1:,[21,31]]
    df.columns=["commodity_code","dollar_value"]
    # only include six-digit commodity codes
    df=df[df["commodity_code"].apply(lambda x: len(str(x))==6)]
    if len(df)<20:
        raise ValueError
    df.to_csv(PATH+"/"+str(reporter_code)+".csv")
    return df

In [ ]:
https://comtrade.un.org/api/get?max=50000&type=S&freq=A&px=EB02&ps=2022

# Save all countries' export data individually to the PATH folder

for reporter_code in reporter_code_list:
    for year in year_list:
        try:
            get_export(reporter_code,year)
            print(".",end="")
        except KeyboardInterrupt:
            raise
        except:
            print("X",end="")
            pass

In [ ]:
print(581 in reporter_code_list)

False

In [ ]:
df = get_export(784,2023)

In [ ]:
df2 = get_export(8, 2023)

In [ ]:
df2[df2['cmdCode'] == '999999'][['cmdCode',
        'fobvalue', 'reporterCode', 'partnerCode', 'partner2Code', 'period','flowCode']]

,cmdCode,fobvalue,reporterCode,partnerCode,partner2Code,period,flowCode
4282,999999,4.176008e+06,8,0,724,2023,X
4283,999999,7.648707e+03,8,0,724,2023,X
4284,999999,2.625426e+06,8,0,724,2023,X
4285,999999,1.542934e+06,8,0,724,2023,X
4286,999999,1.544958e+05,8,0,752,2023,X
...,...,...,...,...,...,...,...
13274,999999,2.477194e+05,8,0,807,2023,X
14599,999999,9.565031e+07,8,0,807,2023,X
14601,999999,8.726131e+05,8,0,818,2023,X
14609,999999,2.326606e+06,8,0,826,2023,X
14619,999999,8.356627e+05,8,0,899,2023,X

In [ ]:
df2.columns

Index(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'period',
       'reporterCode', 'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc',
       'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code',
       'partner2ISO', 'partner2Desc', 'classificationCode',
       'classificationSearchCode', 'isOriginalClassification', 'cmdCode',
       'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc',
       'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty',
       'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty',
       'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt',
       'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue',
       'legacyEstimationFlag', 'isReported', 'isAggregate'],
      dtype='object')

# Merge into mega csvs

merge_all(PATH,year_list)

In [ ]:
year_list

array([2019, 2020, 2021, 2022, 2023])

# Add Service data to the mega dataset

In [ ]:
get_service(year=2022)

SSLError: ignored